version: '2.1'
services:
  jenkins:
    image: 'jenkins/jenkins:latest'
    ports:
      - '80:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
    - './jenkins_data:/var/jenkins_home'
    - '/tmp/:/tmp/'
    
networks:
  test:
   external:
    name: sonarqube_sonarnet

